services:
  dataconnect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "40000:40000"
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:40000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
